### ISSUE TITLE
Criar  App Users

### ISSUE THREAD

**Issue by lucaslmmanoel** [fabricasoftwares/pope#3]
App de usuários do portal de pesquisas POPE

App Users conterá:
- Nome;
- Login através de nome de Usuário;
- E-mail;
- Tipo de usuário;
- Senha;
- Status;
- Organização.

-> Será permitido: Salvar, Atualizar e Ativar; Os administradores gerais serão incumbidos disso.

.Terão Acesso: Os Agentes, os prestadores e os administradores gerais.

Quem são:

-Os Agentes:
Serão incumbidos de verificar dados cadastrados e lista-los de acordo com a necessidade.

-Os Prestadores:
O prestador solicitará a inserção dos seus dados para listagem. Possibilitando também possívels atualizações de informações com posterior aprovação dos Administradores Gerais.

-Administração Geral:
Área que será responsável por cadastrar e manusear os dados dos prestadores.
Aqui, pode-se validar, autenticar, alterar, deletar e inserir os cadastros e informações.

OBS: Caso Não exista um serviço prestado, apenas o administrador geral podera incluir.

**Comment by kimuraz** [comment]
Acho que essas são as models

**Comment by kimuraz** [comment]
Posso separar essa issue em outras pra especificar cada um dos apps?

**Comment by lucaslmmanoel** [comment]
Os apps já demandam as models não?
Fica melhor mesmo dividir os apps em issues!

Em qui, 19 de abr de 2018 1:02 PM, Jose Eduardo Kimura <
notifications@github.com> escreveu:

**Comment by kimuraz** [comment]
Como está definido o padrão de matrícula? Há documentação para essa definição?

**Comment by lucaslmmanoel** [comment]
O padrão para quem já possui são 7 caracteres sendo o primeiro uma letra e
o restante numeros, creio que podemos seguir este mesmo para facilitar,
porem quem não possui matricula temos de gera-la, com esse mesmo padrão

Em dom, 27 de mai de 2018 12:14, Jose Eduardo Kimura <
notifications@github.com> escreveu:

**Comment by kimuraz** [comment]
A letra e os números são aleatórios?

**Comment by lucaslmmanoel** [comment]
P999999 : prestador
A999999 : agente
S999999 : admin superuser

Em seg, 28 de mai de 2018 09:55, Jose Eduardo Kimura <
notifications@github.com> escreveu:
