### ISSUE TITLE
Definição das cores padrões da aplicação

### ISSUE THREAD

**Issue by lucaslmmanoel** [fabricasoftwares/pope#9]
Definição das cores que iremos utilizar na aplicação, e iniciação dos protótipos de tela!!![_home_lucas_Documents_popeProt_node_modules_mdbootstrap_index.html(Nexus 5X) (3).png](https://images.zenhubusercontent.com/5ad56abe4b5806bc2bcf615a/55a592e1-2a46-4a23-8656-0524193013fe)

**Comment by lucaslmmanoel** [comment]
Este modelo foi aprovado pelo cliente e é partir dele que daremos continuidade no projeto, partindo agora para criar um padrão de formulário...

**Comment by kimuraz** [comment]
Acredito que essa issue só deva ser fechada quando houver uma paleta de cores especificada, definida e documentada

**Comment by lucaslmmanoel** [comment]
A cor utilizada até então foi a blue, com um darken 4 presente no framework que iremos utilizar o materilalize...

**Comment by kimuraz** [comment]
E as demais? (Cores de letras, botões, cor secundária, etc)

**Comment by lucaslmmanoel** [comment]
Beleza irei atrás de documentar esses detalhes, e enviarei o anexo contendo
essas informações e logo montaremos um padrão?

2018-06-05 11:40 GMT-03:00 Jose Eduardo Kimura <notifications@github.com>:
